### ISSUE TITLE
Download img file Version 0.3 failes

### ISSUE THREAD

**Issue by B369** [dgarage/hack0-armbian#1]
Trying to download the 9.3 GB image file (Version 0.3) After around 1 GB the download always fails.
Suggestions:
- add a torrent link
- make the file smaller (It's fine to sync the whole blockchain from scratch ;-)

------------------------------------------------------------------------------------------------------

Version 0.3
Image: https://hack0distrib.blob.core.windows.net/public/hack0-rockpro64-0.3.img sha256sum: 0c303cdba9c6bfb7bbfb4d3848d5604fe1311b30cf66e8832cfb0d4b78065ad2 Release date: 15 october 2020

**Comment by Eskyee** [comment]
No problems with downloading... hack0 image, just needs storage space to download and extract.. on your hard drive. No storage space. The Download will fail..

**Comment by B369** [comment]
Finally could download it. Internet browsers didn't work. With a Download Manger it worked.

**Comment by B369** [comment]
Finally could download it. Internet browsers didn't work. With a Download Manger it worked. Used KGet for Linux.

**Comment by Eskyee** [comment]
Had a few problems on a Mac 💻 but worked in the end, I had mentioned it before to @NicolasDorier about downloading problems!! You are correct

**Comment by NicolasDorier** [comment]
thanks can you try again? I tried to change the http headers.

**Comment by B369** [comment]
Just tried 3 times to download  the .img file through some internet browsers again. Still fails

**Comment by NicolasDorier** [comment]
hey @B369 sorry for the delay. What happen exactly? You start downloading and it stop suddenly? (don't hesitate to ping me directly on chat.btcpayserver.org if I'm slow to reply here)

**Comment by NicolasDorier** [comment]
I am closing this, we now upload on aws, so there shouldn't be any problem anymore
